### ISSUE TITLE
Scorehud addon

### ISSUE THREAD

**Issue by MrNinja008** [ErikPDev/VoteParty#1]
Is there vote party addon which shows 25/30 in scorehud for vote party?

**Comment by ErikPDev** [comment]
I'll add it to the next version. I'll most likely release very soon.

**Comment by ErikPDev** [comment]
I've submitted a update to poggit to add support to ScoreHUD
You can download it using the link below
https://poggit.pmmp.io/r/126410/VoteParty_dev-16.phar
Or view the other builds https://poggit.pmmp.io/ci/ErikPDev/VoteParty/VoteParty
Example: §a{voteparty.totalVotes} §c/ §d{voteparty.maxVotes}
| Tag                  | Description                     |
|----------------------|---------------------------------|
| voteparty.totalVotes | Shows the votes to voteparty    |
| voteparty.maxVotes   | Default votes to voteparty      |
